### ISSUE TITLE
DateTimeFixed and DeltaTime not actually exposed

### ISSUE THREAD

**Issue by bohdloss** [iganev/rhai-chrono#1]
Hello, I've tried using this crate but unfortunately it's not possible because the `DateTimeFixed` and `DeltaTime` are in a module marked as `pub(crate)`

**Comment by iganev** [comment]
This is more or less intended. The rhai package exposes `DateTimeFixed` and `Timedelta` through the macro generated package module `ChronoPackage`, but not directly. 

Take a look at the `README.md` file for detailed explanation on how to initialize the rhai module.

Here's a quick and dirty demo to try yourself:

```cargo init --bin```

Then edit `Cargo.toml` to have the following dependencies:

```
[dependencies]
anyhow = { version = "1" }
rhai = { version = "^1.15" }
rhai-chrono = { version = "^0" }
```

Then edit `main.rs` to look roughly like:

```
use rhai::packages::Package;
use rhai::Engine;
use rhai_chrono::ChronoPackage;

use anyhow::anyhow;
use anyhow::Result;

fn main() -> Result<()> {
    let mut engine = Engine::new();

    let package = ChronoPackage::new();
    package.register_into_engine(&mut engine);

    let result = engine
        .eval::<String>(r#"let dt = datetime_utc(); dt.to_string()"#)
        .map_err(|e| anyhow!("Failed to compile: {:?}", e))?;

    println!("Result: {result}");

    Ok(())
}
```

Then execute `cargo run`. The output I got is `Result: 2025-03-05T18:13:53.427347226+00:00` which is exactly as expected. This indicates that the rhai package was successfully registered in the rhai engine and is able to compile and execute my demo script `let dt = datetime_utc(); dt.to_string()`.

Please let me know if you need any more help with this.

**Comment by bohdloss** [comment]
Maybe I'm just misunderstanding how rhai works in general, I apologize. What I'm trying to do is get out the type directly from the script, like so:
```
let result = engine
    .eval::<DateTime<FixedOffset>>(r#"let dt = datetime_utc(); dt"#)
    .map_err(|e| anyhow!("Failed to compile: {:?}", e))?;

println!("Result: {result}");
```

**Comment by iganev** [comment]
Although technically possible, this is not a good practice for several reasons:
- rhai internal types are primed to be used by the language engine, not by client code
- rhai internal types and their methods have special attributes, input types and output types that are not applicable in client code outside of rhai
- this could potentially lead to undefined behavior

Getting values out of rhai should be done using primitive types yielded at the end of a script execution.

In your particular case it might be easier to return a string representing the internal datetime object and if you need  to do any further operations on that data, you can parse it back into a **real** `chrono::DateTime` using some of the provided `from_` constructors.

**Comment by bohdloss** [comment]
I fixed it so I'm gonna write here what I did:
I cloned the repo and modified it to expose the `DateTimeFixed` and `TimeDelta` wrapper types,
And then I got the values out of the script by doing this:
```
let result: DateTime<FixedOffset> = engine
    .eval::<rhai_chrono::datetime::datetime_module::DateTimeFixed>(r#"let dt = datetime_utc(); dt"#)
    .map(|time| Rc::into_inner(time).unwrap().into_inner())
    .map_err(|e| anyhow!("Failed to compile: {:?}", e))?;

println!("Result: {result}");
```
It's definitely very hacky, but it does work.

**Comment by iganev** [comment]
Whatever works for you! 😸 I am still not entirely sure why you need to surface this type outside of the rhai engine though...
